[project]
name = "ComfyUI_Antonioilev"
description = "Antonioilev Light Pack - practical ComfyUI nodes for 3D workflows, mesh repair, UV processing, PBR previews and texture tools."
version = "1.0.8"
license = { file = "LICENSE.txt" }
dependencies = []

[project.urls]
Repository = "https://github.com/Antonioilev/ComfyUI_Antonioilev_Lightpack"

[tool.comfy]
PublisherId = "antonioilev"
DisplayName = "Antonioilev"
Icon = "Antonioilev_logo.png"